In [2]:
"""
Data Science : la librairie pandas
Lien : https://www.youtube.com/watch?v=vmEHCJofslg

Les conditions :
Lorsqu'il y a telle condition... modifier par...

Éditeur : Laurent REYNAUD
Date : 30-06-2021
"""

'\nData Science : la librairie pandas\nLien : https://www.youtube.com/watch?v=vmEHCJofslg\n\nhttps://youtu.be/vmEHCJofslg?t=2588\n\nÉditeur : Laurent REYNAUD\nDate : 30-06-2021\n'

In [2]:
import pandas as pd

In [3]:
# Récupération du fichier .csv
df_csv = pd.read_csv('data/pokemon_data.csv')

In [4]:
"""Recours à une condition
Pour les Pokemon de type 'Fire' afficher 'True' dans
champ 'Legendary'"""
df_csv.loc[df_csv['Type 1'] == 'Fire', 'Legendary'] = True

In [6]:
df_csv.head(50)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,True
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,True
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,True
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,True
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,True
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
24,19,Rattata,Normal,NaN,30,56,35,25,35,72,1,False
25,20,Raticate,Normal,NaN,55,81,60,50,70,97,1,False
26,21,Spearow,Normal,Flying,40,60,30,31,31,70,1,False
27,22,Fearow,Normal,Flying,65,90,65,61,61,100,1,False
28,23,Ekans,Poison,NaN,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,60,85,69,65,79,80,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
31,26,Raichu,Electric,NaN,60,90,55,90,80,110,1,False
32,27,Sandshrew,Ground,NaN,50,75,85,20,30,40,1,False
33,28,Sandslash,Ground,NaN,75,100,110,45,55,65,1,False
34,29,Nidoran (Female),Poison,NaN,55,47,52,40,40,41,1,False
35,30,Nidorina,Poison,NaN,70,62,67,55,55,56,1,False
36,31,Nidoqueen,Poison,Ground,90,92,87,75,85,76,1,False
37,32,Nidoran (Male),Poison,NaN,46,57,40,40,40,50,1,False
38,33,Nidorino,Poison,NaN,61,72,57,55,55,65,1,False
39,34,Nidoking,Poison,Ground,81,102,77,85,75,85,1,False
40,35,Clefairy,Fairy,NaN,70,45,48,60,65,35,1,False
41,36,Clefable,Fairy,NaN,95,70,73,95,90,60,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,True
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,True
44,39,Jigglypuff,Normal,Fairy,115,45,20,45,25,20,1,False
45,40,Wigglytuff,Normal,Fairy,140,70,45,85,50,45,1,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
47,42,Golbat,Poison,Flying,75,80,70,65,75,90,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False

In [5]:
# Récupération du fichier modified.csv
df_csv = pd.read_csv('data/modified.csv')

In [7]:
df_csv.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [9]:
"""Recours à 2 conditions
Pour les Pokemon avec un total > 500 remplacement des
champs 'Generation' et 'Legendary' par 'TEST VALUE'"""
df_csv.loc[df_csv['Total'] > 500, ['Generation', 'Legendary']] = 'TEST VALUE'

In [10]:
df_csv

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,TEST VALUE,TEST VALUE
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,TEST VALUE,TEST VALUE
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,TEST VALUE,TEST VALUE
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,TEST VALUE,TEST VALUE
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,TEST VALUE,TEST VALUE
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,TEST VALUE,TEST VALUE
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,TEST VALUE,TEST VALUE

In [11]:
"""Recours à 2 conditions
Pour les Pokemon avec un total > 500 remplacement des
champs 'Generation' et 'Legendary' par :
-> 'Test 1' pour le champ 'Generation'
-> 'Test 2' pour le champ 'Legendary"""
df_csv.loc[df_csv['Total'] > 500, ['Generation', 'Legendary']] = ['Test 1', 'Test 2']

In [13]:
df_csv

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Test 1,Test 2
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,Test 1,Test 2
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,Test 1,Test 2
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,Test 1,Test 2
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,Test 1,Test 2
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,Test 1,Test 2
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,Test 1,Test 2